REPO=https://raw.githubusercontent.com/github/gitignore/refs/heads/main

all: Julia.gitignore OCaml.gitignore Python.gitignore R.gitignore Rails.gitignore TeX.gitignore
	curl -LO $(REPO)/$<

Julia.gitignore:
	curl -LO $(REPO)/Julia.gitignore

Kotlin.gitignore:
	curl -LO $(REPO)/Kotlin.gitignore

OCaml.gitignore:
	curl -LO $(REPO)/OCaml.gitignore

Python.gitignore:
	curl -LO $(REPO)/Python.gitignore

R.gitignore:
	curl -LO $(REPO)/R.gitignore

Racket.gitignore:
	curl -LO $(REPO)/Racket.gitignore

Rails.gitignore:
	curl -LO $(REPO)/Rails.gitignore

Ruby.gitignore:
	curl -LO $(REPO)/Ruby.gitignore

Rust.gitignore:
	curl -LO $(REPO)/Rust.gitignore

Scheme.gitignore:
	curl -LO $(REPO)/Scheme.gitignore

TeX.gitignore:
	curl -LO $(REPO)/TeX.gitignore

Terraform.gitignore:
	curl -LO $(REPO)/Terraform.gitignore

VisualStudio.gitignore:
	curl -LO $(REPO)/VisualStudio.gitignore
